spring:
  output:
    ansi:
      enabled: always
  profiles:
    active:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:26257/demo?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      auto-commit: true
      catalog: public
      transaction-isolation: TRANSACTION_SERIALIZABLE
      # The property controls the maximum size that the pool is allowed to reach,
      # including both idle and in-use connections.
      maximum-pool-size: 500
      # The property controls the minimum number of idle connections that HikariCP
      # tries to maintain in the pool, including both idle and in-use connections.
      minimum-idle: 0
      # The number of milliseconds before the pool initialization fails, or 0 to
      # validate connection setup but continue with pool start, or less than zero to
      # skip all initialization checks and start the pool without delay.
      initialization-fail-timeout: -1
      # Set the maximum number of milliseconds that a client will wait for a connection from the pool.
      connection-timeout: 3000
      # Sets the maximum number of milliseconds that the pool will wait for a connection to be validated as alive.
      validation-timeout: 5000
      # Controls the maximum amount of time that a connection is allowed to sit idle in the pool.
      # Must be lower than max-lifetime, lowest is 10s
      idle-timeout: 10000
      # Controls the maximum lifetime of a connection in the pool. When a connection reaches this timeout,
      # even if recently used, it will be retired from the pool. An in-use connection will never be retired,
      # only when it is idle will it be removed.
      # Lowest possible value is 30s.
      max-lifetime: 30000
      # Controls the keepalive interval for a connection in the pool.
      keepalive-time: 0
#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) [%t] %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:%5p} [%t] %logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: .log/demo.log
  logback:
    rollingpolicy:
      max-history: 3